
CREATE TABLE ADMIN(
  ADMIN_ID INT NOT NULL,
  USERNAME VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(15) NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY(ADMIN_ID)
);

CREATE TABLE USERS(
  USER_ID INT NOT NULL,
  USERNAME VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(15) NOT NULL, 
  PRIMARY KEY(USER_ID,USERNAME)
);

CREATE TABLE DONOR(
  DONOR_ID INT NOT NULL,
  FNAME VARCHAR(30) NOT NULL,
  LNAME VARCHAR(30) NOT NULL,
  GENDER CHAR(7),
  DOB DATE NOT NULL,
  QUANTITY INT,
  BLOOD_GRP CHAR(10) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  CONTACT CHAR(10) NOT NULL,
  USERNAME VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(15) NOT NULL,
  PRIMARY KEY(DONOR_ID),
  FOREIGN KEY(DONOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE RECIPIENT(
  RECPT_ID INT NOT NULL,
  FNAME VARCHAR(30) NOT NULL,
  LNAME VARCHAR(30) NOT NULL,
  GENDER CHAR(7),
  DOB DATE NOT NULL,
  BLOOD_GRP CHAR(10) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  CONTACT CHAR(10) NOT NULL,
  USERNAME VARCHAR(15) NOT NULL,
  PASSWORD VARCHAR(15) NOT NULL,
  PRIMARY KEY(RECPT_ID),
  FOREIGN KEY(RECPT_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);


CREATE TABLE ANNOUNCEMENT(
  ANNOUNCE_ID INT NOT NULL,
  EVENT_DATE DATE NOT NULL,
  ANNOUNCEMENT VARCHAR(50) NOT NULL,
  REQUIREMENTS VARCHAR(75) NOT NULL,
  ORGANIZER VARCHAR(20),
  BLOOD_NEED VARCHAR(20),
  PRIMARY KEY(ANNOUNCE_ID)
);

INSERT INTO ADMIN VALUES(101,'fmullers','54xya','Fr.Mullers');
SELECT * FROM ADMIN;

INSERT INTO USERS VALUES(101201,'jake_456','654effg');
INSERT INTO USERS VALUES(101202,'thea_789','786efg');
INSERT INTO USERS VALUES(101203,'sebs_012','34pqt');
SELECT * FROM USERS;


INSERT INTO DONOR VALUES(101201,'Jacob','Faustin','Male','1997-09-03',3,'O+','jake258@gmail.com','Lalbagh,Mangalore-575003','9874563210','jake_456','654effg');
INSERT INTO DONOR VALUES(101202,'Thea','June','Female','2002-10-22',2,'AB-','theajune@gmail.com','Mangalore-575002','8796543210','thea_789','786efg');
SELECT * FROM DONOR;

INSERT into RECIPIENT VALUES(101203,'Seb','Stan','Male','1964-02-01','B+','sebs234@gmail.com','Nanthoor, Mangalore-57500','7986541235','sebs_012','34pqt');
INSERT INTO RECIPIENT VALUES(101202,'Thea','June','Female','2002-10-22','AB-','theajune@gmail.com','Kadri, Mangalore-575002','8796543210','thea_789','786efg');
SELECT * FROM RECIPIENT;



INSERT INTO ANNOUNCEMENT VALUES(001,'2022-12-20','Blood Donation Camp','You must be in good health','NCC','Atleast 2 units');
INSERT INTO ANNOUNCEMENT VALUES(002,'2023-02-05','Blood Donation Camp','You must be in good health','RED CROSS','3 units of platelets');
INSERT INTO ANNOUNCEMENT VALUES(003,'2023-02-04','Blood Donation Awareness','Student','RED CROSS','');

SELECT * FROM ANNOUNCEMENT;



















